spring:
  application:
    name: elasticsearch-example
  elasticsearch:
    rest:
      uris: 127.0.0.1:9201
      read-timeout: 3s

logging:
  level:
    root: info

server:
  port: 8093





#
#elasticsearch:
#  ip: 127.0.0.1
#  port: 9200
#  user:
#  password:
#  connectTimeout: 1000
#  socketTimeout: 40000
#  connectionRequestTimeout: 1000
#  maxConnTotal: 100
#  maxConnPerRoute: 100
#  maxRetryTimeoutMillis: 300000